/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_rapphim;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;



/**
 *
 * @author Josheph
 */
public class DangNhap extends javax.swing.JFrame {

    public DangNhap() {
        initComponents();
        setLocationRelativeTo(this);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpg")));
        scaleImageLabel("login.jpg", lblbg);
    }
    
    public  void scaleImageLabel(String image, JLabel lbl){
        ImageIcon icon = new ImageIcon(getClass().getResource(image));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        lbl.setIcon(scaleIcon);
    }
   
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        txtMK = new javax.swing.JPasswordField();
        btnDN = new javax.swing.JButton();
        btnDK = new javax.swing.JButton();
        btnLL = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboQuyen = new javax.swing.JComboBox<>();
        lblbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 0, 450, 110);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 520, 110);

        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài Khoản");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 170, 70, 40);

        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mật Khẩu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 270, 70, 40);
        jPanel1.add(txtTK);
        txtTK.setBounds(160, 160, 250, 50);
        jPanel1.add(txtMK);
        txtMK.setBounds(160, 260, 250, 50);

        btnDN.setBackground(new java.awt.Color(255, 102, 102));
        btnDN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDN.setText("Đăng Nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        jPanel1.add(btnDN);
        btnDN.setBounds(20, 460, 110, 60);

        btnDK.setBackground(new java.awt.Color(255, 102, 102));
        btnDK.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDK.setText("Đăng Ký");
        btnDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKActionPerformed(evt);
            }
        });
        jPanel1.add(btnDK);
        btnDK.setBounds(150, 460, 100, 60);

        btnLL.setBackground(new java.awt.Color(255, 102, 102));
        btnLL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLL.setText("Làm Lại");
        jPanel1.add(btnLL);
        btnLL.setBounds(270, 460, 100, 60);

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat);
        btnThoat.setBounds(390, 460, 100, 60);

        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quyền Đăng Nhập");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 350, 110, 50);

        cboQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amin", "User" }));
        jPanel1.add(cboQuyen);
        cboQuyen.setBounds(160, 350, 250, 50);
        jPanel1.add(lblbg);
        lblbg.setBounds(0, 110, 510, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        String taikhoan = txtTK.getText();
        String matkhau = String.valueOf(txtMK.getPassword());
        matkhau = Connect.MD5(matkhau);
        String err = null;
        err = Connect.getConnection();
        if(! err.equals("")){
                JOptionPane.showConfirmDialog(this, err, "Lỗi", JOptionPane.ERROR_MESSAGE);
                txtTK.setText("");
                txtMK.setText("");
        }else 
            if(taikhoan.equals("") || matkhau.equals("")){
            JOptionPane.showConfirmDialog(this, "Bạn phải nhập đầy đủ", "Lỗi", JOptionPane.ERROR);
            }else{
                String sql = "select * from Users where tai_khoan = ? and mat_khau = ? and quyen = ?;";
                PreparedStatement pstmt;
                try{
                   pstmt = Connect.conn.prepareStatement(sql); 
                   pstmt.setString(1, taikhoan);
                   pstmt.setString(2, matkhau);
                   pstmt.setString(3, String.valueOf(cboQuyen.getSelectedItem()));
                   if(cboQuyen.getSelectedIndex() == 0){
                       Main m = new Main();
                   this.dispose();
                   m.setVisible(true);
                   }else{
                       Main_User mu = new Main_User();
                       mu.setVisible(true);
                       this.dispose();
                   }
                   }catch(SQLException ex){
                       JOptionPane.showConfirmDialog(this, ex, "Lỗi", JOptionPane.INFORMATION_MESSAGE);
                }
            }
    }//GEN-LAST:event_btnDNActionPerformed

    private void btnDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKActionPerformed
        // TODO add your handling code here:
        DangKy dk = new DangKy();
        this.dispose();
        dk.setVisible(true);
    }//GEN-LAST:event_btnDKActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDK;
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnLL;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblbg;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
