/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_rapphim;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josheph
 */
public class QL_Phim extends javax.swing.JFrame {

    boolean them;
    DefaultTableModel dtm = new DefaultTableModel();
    String sql = null;
    
    public QL_Phim() {
        initComponents();
        loadData();
        setLocationRelativeTo(this);
        activeControl(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpg")));
    }

    public void loadData(){
   
        String errString = Connect.getConnection();
        Statement stmt;
        if(!errString.equals("")){
            JOptionPane.showConfirmDialog(this, errString, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else {
            sql = "select * from phim;";
            try{
              stmt = Connect.conn.createStatement();
              try(ResultSet rs = stmt.executeQuery(sql)){
                  ResultSetMetaData rsmd = rs.getMetaData();
                  int n = rsmd.getColumnCount();
                  Vector col, row;
                  col = new Vector();
                  for (int i = 1; i <= n; i++) {
                      col.add(rsmd.getColumnName(i));
                  }
                  dtm.setColumnIdentifiers(col);
                  while (rs.next()) {                      
                      row = new Vector();
                      for (int i = 1; i <= n; i++) {
                          row.addElement(rs.getString(i));
                      }
                      dtm.addRow(row);
                      tblNhanVien.setModel(dtm);
                  }
                  tblNhanVien.getSelectionModel().addListSelectionListener(((e) -> {
                        if(tblNhanVien.getSelectedRow() >= 0){
                            txtID.setText((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 0));
                            txtName.setText((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 1));
                            txtTL.setText((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 2));
                            txtTuoi.setText((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 3));
                            txtQuocGia.setText((String) tblNhanVien.getValueAt(tblNhanVien.getSelectedRow(), 4));
                        }
                    }));
              }
              stmt.close();
              
            }catch(SQLException ex){
                JOptionPane.showConfirmDialog(this, ex.getMessage(),"Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        
        }
        
    }
    
    public void activeControl(boolean status){
        btnAdd.setVisible(!status);
        btnDelete.setVisible(!status);
        btnUpdate.setVisible(!status);
        btnSave.setVisible(status);
        btnNoSave.setVisible(status);
        txtID.setEditable(status);
        txtName.setEditable(status);
        txtTL.setEditable(status);
        txtQuocGia.setEditable(status);
        txtTuoi.setEditable(status);
        txtID.setVisible(!status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        txtQuocGia = new javax.swing.JTextField();
        txtTL = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnNoSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ PHIM");

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHIM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 700, 110);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 740, 130);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(81, 14, 14), new java.awt.Color(255, 102, 102)));
        jPanel3.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã Phim:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 30, 100, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên Phim:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 110, 100, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thời Lượng:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 190, 100, 40);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Độ Tuổi:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(370, 30, 100, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quốc Gia:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(370, 110, 100, 40);
        jPanel3.add(txtID);
        txtID.setBounds(140, 30, 210, 40);
        jPanel3.add(txtName);
        txtName.setBounds(140, 110, 210, 40);
        jPanel3.add(txtTuoi);
        txtTuoi.setBounds(470, 30, 210, 40);
        jPanel3.add(txtQuocGia);
        txtQuocGia.setBounds(470, 110, 210, 40);
        jPanel3.add(txtTL);
        txtTL.setBounds(140, 190, 210, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 140, 700, 270);

        btnDelete.setBackground(new java.awt.Color(102, 102, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 204));
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(110, 440, 90, 40);

        btnUpdate.setBackground(new java.awt.Color(102, 102, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 204));
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(210, 440, 90, 40);

        btnExit.setBackground(new java.awt.Color(102, 102, 0));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 204));
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(620, 440, 90, 40);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phim", "Tên Phim", "Thời Lượng", "Độ Tuổi", "Quốc Gia"
            }
        ));
        jScrollPane1.setViewportView(tblNhanVien);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 500, 700, 230);

        btnSave.setBackground(new java.awt.Color(102, 102, 0));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 204));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(370, 440, 90, 40);

        btnAdd.setBackground(new java.awt.Color(102, 102, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 204));
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(10, 440, 90, 40);

        btnNoSave.setBackground(new java.awt.Color(102, 102, 0));
        btnNoSave.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnNoSave.setForeground(new java.awt.Color(255, 255, 204));
        btnNoSave.setText("Không Lưu");
        btnNoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnNoSave);
        btnNoSave.setBounds(490, 440, 111, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String errString = Connect.getConnection();
        if(!errString.equals("")){
            JOptionPane.showConfirmDialog(this, errString, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            PreparedStatement pstmt;
            sql = "delete from phim where ma_phim = ?";
            try{
                pstmt = Connect.conn.prepareCall(sql);
                pstmt.setInt(1, Integer.parseInt(txtID.getText()));
                int kq = pstmt.executeUpdate();
                if(kq>0){
                    JOptionPane.showConfirmDialog(this, "Bạn đã xóa thành công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
                dtm.setRowCount(0);
                loadData();

            }catch(SQLException ex){
                JOptionPane.showConfirmDialog(this, ex.getMessage(), "Lổi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        them = false;
        activeControl(true);
        txtID.setEditable(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String errsString = Connect.getConnection();
        if(!errsString.equals("")){
            JOptionPane.showConfirmDialog(this, errsString, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                PreparedStatement pst;
                sql = "insert into phim(ten_phim, thoi_luong, do_tuoi, quoc_gia) values (?, ?, ?, ?);";
                if(them){
                    pst = Connect.conn.prepareCall(sql);
                    pst.setString(1, txtName.getText());
                    pst.setInt(2, Integer.parseInt(txtTL.getText()));
                    pst.setInt(3, Integer.parseInt(txtTuoi.getText()));
                    pst.setString(4, txtQuocGia.getText());
            
                }else{
                    sql="update phim set ten_phim = ?, thoi_luong = ?, do_tuoi = ?, quoc_gia = ? where ma_phim= ?";
                    pst = Connect.conn.prepareCall(sql);
                    pst.setInt(5, Integer.parseInt(txtID.getText()));
                    pst.setString(1, txtName.getText());
                    pst.setInt(2, Integer.parseInt(txtTL.getText()));
                    pst.setInt(3, Integer.parseInt(txtTuoi.getText()));
                    pst.setString(4, txtQuocGia.getText());
                }
                int kq = pst.executeUpdate();
                if(kq>0){
                    if(them){
                        JOptionPane.showConfirmDialog(this, "Đã thêm thành công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                        them = false;
                    }else{
                        JOptionPane.showConfirmDialog(this, "Đã sửa thành công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    }
                    dtm.setRowCount(0);
                    loadData();
                    activeControl(false);
                }
            }catch(SQLException ex){
                JOptionPane.showConfirmDialog(this, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        txtID.setVisible(false);
        them = true;
        activeControl(true);
        txtName.requestFocus();
        txtName.setText("");
        txtTuoi.setText("");
        txtQuocGia.setText("");
        txtTL.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnNoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoSaveActionPerformed
        // TODO add your handling code here:
        them = false;
        loadData();
        activeControl(false);
        tblNhanVien.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_btnNoSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_Phim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_Phim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_Phim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_Phim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_Phim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNoSave;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuocGia;
    private javax.swing.JTextField txtTL;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
